# -*- coding: utf-8 -*-
"""Contour plots.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j4rf0eEftBeZ27irP4IhRFtcKiyrRSPA

This is illustrating Countour plots
"""

import numpy as np

import matplotlib.pyplot as plt

def fun (x,y):
  return np.sin(x)**2 + np.cos(y)**2
  x = np.linspace(0,5,50)
  y= np.linspace(0,5,50)

X,Y = np.meshgrid(x,y)
Z= fun (X,Y)

plt.contour (X,Y,Z, cmap='gist_rainbow_r');

